### PR TITLE
feat: Standalone dash

### LINKED ISSUE #20: Provide a docker config for bahis-data and bahis-dash
### Problem

We need to be able to deploy using docker

### Desired Solution

Ultimatelly it will be in a same docker-compose file as the rest of the bahis setup but we are starting and making it work on its own

### Considered Alternatives

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mixmixmix**
## Description

Provides docker-compose configuration for dashboard and data pipeline.

closes https://github.com/road86/bahis-infra/issues/20

Instructions how to use and what additional files to use here: https://github.com/road86/bahis-infra/tree/standalone-dash/deploy_dash#readme

### CODE REVIEW

**Comment by shaarful** [comment]
@mixmixmix where is the dash-db directory for copying `secret-init_user.sql` this files? I think it is better to add copy command in Dockerfile as  `secret-init_user.sql` is required.

**Review by shaarful — COMMENTED** [review]
Getting this error 
`Traceback (most recent call last):
  File "index.py", line 20, in <module>
    app = Dash(__name__, 
  File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 511, in __init__
    self.init_app()
  File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 589, in init_app
    self.enable_pages()
  File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 2040, in enable_pages
    _import_layouts_from_pages(self.config.pages_folder)
  File "/usr/local/lib/python3.10/site-packages/dash/_pages.py", line 435, in _import_layouts_from_pages
    spec.loader.exec_module(page_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/bahis-dash/pages/dls.py", line 40, in <module>
    geofilename = glob.glob(sourcepath + 'newbahis_geo_cluster*.csv')[-1]   # the available geodata from the bahis project (Masterdata)
IndexError: list index out of range
unable to load app 0 (mountpoint='') (callable not found or import error)`

**Comment by shaarful** [comment]
> Getting this error `Traceback (most recent call last): File "index.py", line 20, in <module> app = Dash(__name__, File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 511, in __init__ self.init_app() File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 589, in init_app self.enable_pages() File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 2040, in enable_pages _import_layouts_from_pages(self.config.pages_folder) File "/usr/local/lib/python3.10/site-packages/dash/_pages.py", line 435, in _import_layouts_from_pages spec.loader.exec_module(page_module) File "<frozen importlib._bootstrap_external>", line 883, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/bahis-dash/pages/dls.py", line 40, in <module> geofilename = glob.glob(sourcepath + 'newbahis_geo_cluster*.csv')[-1] # the available geodata from the bahis project (Masterdata) IndexError: list index out of range unable to load app 0 (mountpoint='') (callable not found or import error)`

Found the problem. @mixmixmix You are pointed the wrong sourcepath.

**Comment by mixmixmix** [comment]
> @mixmixmix where is the dash-db directory for copying `secret-init_user.sql` this files? I think it is better to add copy command in Dockerfile as `secret-init_user.sql` is required.

This is part of bahis-infra config and goes to `bahis-infra`  `dash-db` config. There might be a better way to deal with secrets but it should be repo wise I think

**Comment by mixmixmix** [comment]
> Found the problem. @mixmixmix You are pointed the wrong sourcepath.

Can you provide more detail or push a fish here? I must have missed it when testing.

**Comment by shaarful** [comment]
There should be an empty `exported_data` directory or make directory if not exist. Otherwise `nightly.sh` scripts will not find the directory for copy. I have manually created one. same for `dash-db` directory

But @mixmixmix , Is cron running at the scheduled time? I did not notice that. may be my bad. Otherwise, it is ok.

**Comment by mixmixmix** [comment]
> `db`



> There should be an empty `exported_data` directory or make directory if not exist. Otherwise `nightly.sh` scripts will not find the directory for copy. I have manually created one. same for `dash-db` directory

As per your suggestion creation of directory is added to `bahis-data`. `dash-db` dir is now commited with a readme file reminding about our secrets.

> But @mixmixmix , Is cron running at the scheduled time? I did not notice that. may be my bad. Otherwise, it is ok.

It is running nightly. I tested it that it works at a shorter interval.

**Comment by shaarful** [comment]
> > `db`
> 
> > There should be an empty `exported_data` directory or make directory if not exist. Otherwise `nightly.sh` scripts will not find the directory for copy. I have manually created one. same for `dash-db` directory
> 
> As per your suggestion creation of directory is added to `bahis-data`. `dash-db` dir is now commited with a readme file reminding about our secrets.
> 
> > But @mixmixmix , Is cron running at the scheduled time? I did not notice that. may be my bad. Otherwise, it is ok.
> 
> It is running nightly. I tested it that it works at a shorter interval.

If cron jobs work then I have no issue. 
But I had to run manually nightly.sh at first time of docker configuration. But I agree it is a one-time job only.

**Review by shaarful — APPROVED** [review]
agreed

**Pull request merged**
